### ISSUE TITLE
Telex is not org aware

### ISSUE THREAD

**Issue by brettgoulder** [heroku/telex#43]
If you are an org admin, and a collaborator on that same app, you will receive notifications twice.

We should fix this so these customers just get a single email.

**Comment by will** [comment]
As long as it is true that the org api is a public one, and given only a UUID of an app, you can find the org's owners, (`AppUserFinder`)[https://github.com/heroku/telex/blob/master/lib/mediators/messages/user_finder.rb#L75-L89] could be extended to remove @herokumanager.com addresses, and add the owners in manually.

**Comment by will** [comment]
I will not be able to do this anytime soon, but I am willing to guide someone and review their patch.

**Comment by wuputah** [comment]
https://devcenter.heroku.com/articles/platform-api-reference#organization-member-list

**Comment by wuputah** [comment]
Hi @will, I started working on this in [jd-org-admins](https://github.com/heroku/telex/tree/jd-org-admins), but I am foreseeing a problem--the org API above does not return user IDs, so the `extract_user` call will fail when using one of these user records.

**Comment by will** [comment]
We should get API to return the user's uuid in that call. It is dangerous
that that endpoint returns only email address which can change at any time
without warning.
